#!/bin/sh -e

suite66_live() {
  if [ ! -d /run/66 ]; then
    echo >&2 "  Skipped: 66 is not running."
    exit 0
  fi
}

svc_help(){
    echo "	==> Start/stop a service:"
    echo "  66-start <service>"
    echo "  66-stop <service>"
}

svc_add_help(){
    echo "	==> Add a service:"
    echo "  66-enable <service>"
    svc_help
}

svc_del_help(){
    echo "	==> Remove a service:"
    echo "  66-disable <service>"
    svc_help
}

reload_dbus() {
  dbus-send --print-reply --system --type=method_call \
            --dest=org.freedesktop.DBus \
            / org.freedesktop.DBus.ReloadConfig > /dev/null
}

each_conf() {
  while read -r f; do
    "$@" "/$f"
  done
}

op="$1"; shift
sv="$2"

case $op in
  sysctl)   suite66_live; each_conf /usr/bin/sysctl -q -p ;;
  binfmt)   suite66_live; /etc/66/script/binfmt.sh ;;
  dbus_reload)  suite66_live; reload_dbus ;;
    # For use by other packages
  add)      svc_add_help ;;
  del)      svc_del_help ;;
  longrun_restart) suite66_live; 66-svctl -r "$sv" ;;
  *) echo >&2 "  Invalid operation '$op'"; exit 1 ;;
esac

exit 0
