#!/bin/sh -e

init_conf(){
    while read -r f; do
        ln -sf "$(basename "$f")" "/usr/bin/init"
        echo "	==> Activated $(basename "$f")"
    done
}

init_detect(){
    artix_inits="openrc-init runit-init s6-init suite66-init"
    for supported in ${artix_inits}; do
        bin=/usr/bin/"$supported"
        if [ -f "$bin" ];then
            init=$(basename "$bin")
        fi
    done

    if [ -n "$init" ];then
        echo "	==> Found $init"
        ln -sf "$init" "/usr/bin/init"
    else
        echo "	==> No supported init found."
    fi
}

case "$1" in
    update) init_conf ;;
    detect) init_detect ;;
    *) echo >&2 "  Invalid operation '$1'"; exit 1 ;;
esac
