#!/bin/bash

# {{{ functions

db_action() {
    s6-rc-db -c "${DBPATH}" "$@"
}

a_newbundle() {
    for j in $new_bundles; do
        if [ "$j" = "$1" ]; then
            return 0
        fi
    done
    return 1
}

service_exists() {
    for k in $all_services; do
        if [ "$k" = "$1" ]; then
            return 0
        fi
    done
    return 1
}

in_newbundle() {
    bundle_contents=$(db_action contents "$1")
    for l in $bundle_contents; do
        if [ "$l" = "$2" ]; then
            return 0
        fi
    done
    return 1
}

# }}}


# main

RCPATH='/etc/s6/rc'
DBPATH="${RCPATH}/compiled"
SVPATH='/etc/s6/sv'
SVDIRS='/run/s6-rc/servicedirs'
TIMESTAMP=$(date +%s)

if [ -e "${DBPATH}" ]; then
    old_bundles="$(db_action list bundles)"
    len=0
    for bundle in $old_bundles; do
        contents[$len]=$(db_action contents "$bundle")
        len=$(( len + 1 ))
    done
fi

if ! s6-rc-compile "${DBPATH}"-"${TIMESTAMP}" "${SVPATH}"; then
    echo "Error compiling database."
    echo "Please double check the ${SVPATH} directories. Exiting."
    exit 1
fi

if [ -e "/run/s6-rc" ]; then
    for dir in "${SVDIRS}"/*; do
        if [ -e "${dir}/down" ]; then
            s6-svc -x "${dir}"
        fi
    done
    s6-rc-update "${DBPATH}"-"${TIMESTAMP}"
fi

if [ -d "${DBPATH}" ]; then
    ln -sf "${DBPATH}"-"${TIMESTAMP}" "${DBPATH}"/compiled && mv -f "${DBPATH}"/compiled "${RCPATH}"
else
    ln -sf "${DBPATH}"-"${TIMESTAMP}" "${DBPATH}"
fi

new_bundles=$(db_action list bundles)
all_services=$(db_action list all)


if [ -n "$old_bundles" ]; then
    len=0
    for m in $old_bundles; do
        old_contents=${contents[$len]}
        a_newbundle "$m"
        ret=$?

        for n in $old_contents; do
            service_exists "$n"
            ret2=$?

            if [ $ret -eq 1 ]; then
                if [ $ret2 -eq 0 ]; then
                    new_contents="$new_contents $n"
                fi
            else
                if [ $ret2 -eq 0 ]; then
                    in_newbundle "$m" "$n"
                    ret3=$?

                    if [ $ret3 -eq 1 ]; then
                        s6-rc-bundle-update -c "${DBPATH}" add "$m" "$n"
                    fi

                fi
            fi

        done

        if [ -n "$new_contents" ]; then
            s6-rc-bundle -c "${DBPATH}" add "$m" $new_contents
        fi

        new_contents=""
        len=$(( len + 1 ))
    done
fi

echo "==> Switched to a new database."
echo "    Remove any old unwanted/unneeded database directories in ${RCPATH}."
