#!/bin/sh -e

s6_live() {
  if [ ! -L /run/s6-rc ]; then
    echo >&2 "  Skipped: s6-rc is not running."
    exit 0
  fi
}

svc_help(){
    echo "	==> Start/stop a service:"
    echo "  s6-rc -u/-d change <service>"
}

svc_add_help(){
    echo "	==> Add a service:"
    echo "  s6-rc-bundle-update add default <service>"
    svc_help
}

svc_del_help(){
    echo "	==> Remove a service:"
    echo "  s6-rc-bundle-update delete default <service>"
    svc_help
}

reload_dbus() {
    dbus-send --print-reply --system --type=method_call \
            --dest=org.freedesktop.DBus \
            / org.freedesktop.DBus.ReloadConfig > /dev/null
}

shutdown_service() {
  while read -r dir; do
    if [ -d "$dir" ] && [ "$dir" != "etc/s6/sv/" ]; then
      sv=$(basename "$dir")
      active=$(s6-rc -a list | grep -Fx "$sv" || true)
      if [ -n $active ]; then
        s6-rc -d change "$sv"
      fi
      if [ -e /run/s6-rc/servicedirs/"$sv" ]; then
        s6-svc -x /run/s6-rc/servicedirs/"$sv"
      fi
    fi
  done
}

restart_service() {
    s6-svc -r /run/service/"$sv"
}

each_conf() {
  while read -r f; do
    "$@" "/$f"
  done
}

op="$1"; shift
sv="$2"

case $op in
  sysctl)   s6_live; each_conf /usr/bin/sysctl -q -p ;;
  binfmt)   s6_live; /etc/s6/sv/binfmt/shell_up ;;
  dbus_reload) s6_live; reload_dbus ;;
    # For use by other packages
  add)      svc_add_help ;;
  del)      svc_del_help ;;
  longrun_restart) s6_live; restart_service ;;
  shutdown_sv) s6_live; shutdown_service ;;
  *) echo >&2 "  Invalid operation '$op'"; exit 1 ;;
esac

exit 0
