#!/bin/bash

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Initializing artix-live script"
        artix-live #|| stat_die
        add_daemon artix-live
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        ;;
esac
